[build]
builder = "NIXPACKS"

[build.env]
NIXPACKS_NODE_VERSION = "18"
NIXPACKS_NPM_VERSION = "8"

[deploy]
startCommand = "node server.js"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
PORT = "3000"